language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
  - "3.4"
install:
  - pip install --upgrade pip
  - pip install feedparser lxml
# command to run tests
script: python Test.py
